### ISSUE TITLE
Nothing is barely faster than anything else? 🤷‍♂️

### ISSUE THREAD

**Issue by joakin** [joakin/js-data-oriented-benchmark#1]
Example run:

```
js-data-oriented-benchmark → NODE_ENV=production node index.js
typed array x 404 ops/sec ±0.82% (80 runs sampled)
array x 404 ops/sec ±0.90% (79 runs sampled)
array of structure x 392 ops/sec ±1.10% (84 runs sampled)
structure of array x 403 ops/sec ±0.96% (81 runs sampled)
Fastest is array,typed array,structure of array

```

**Comment by joakin** [comment]
Hey @niedzielski thoughts? I'm not sure I'm making any basic mistakes here, I would appreciate your input 🙇‍♂️

**Comment by niedzielski** [comment]
@joakin, nothing especially helpful butttt:

- Here's what I get using benchmark v2.1.4 on Node.js v13.0.1 on my laptop:
```
NODE_ENV=production node index.js
typed array x 437 ops/sec ±1.00% (91 runs sampled)
array x 390 ops/sec ±0.65% (93 runs sampled)
array of structure x 384 ops/sec ±1.03% (88 runs sampled)
structure of array x 381 ops/sec ±1.33% (89 runs sampled)
Fastest is typed array
```
- I've always been told to isolate the PRNG implementation to avoid platform implementation differences (e.g., Node.js version or browser differences) as well as system call issues. I would say it doesn't matter if you're the only one running it but here _we_ are. Seeding the PRNG will also allow you to validate the calculations perform the same task with the same inputs / outputs. Lastly, for the typed array, I think you should be more explicit about the conversion: either say that the integer conversion is a tax that the other implementations need or change the Int32Array to a Float64Array or Float32Array.
- I think you need more parameterization in the tests. Presently, only one size is tested for writing. I think you would have a much better sense of where each solution works best and more confidence that your tests were valid if you tried a few sizes for reading, writing, and reading + writing. Then you choose the best for your problem domains.
- It would be nice to characterize the loop + PRNG cost. E.g., if you know it won't be optimized away:
```
for (let i = 0; i < SIZE; i++) {
  (Math.random() * Number.MAX_SAFE_INTEGER) | 0;
}
```

I've attempted to whip something up locally but at least my read test is producing different results for SOA and AOS, maybe due to seeding, so I don't have some initialization quite right:
```
typed array read x 414 ops/sec ±0.49% (87 runs sampled)
array read x 343 ops/sec ±0.29% (91 runs sampled)
array of structure read x 967 ops/sec ±0.77% (93 runs sampled)
structure of array read x 876 ops/sec ±0.36% (93 runs sampled)
Read fastest is array of structure read

typed array write x 652 ops/sec ±0.22% (97 runs sampled)
array write x 655 ops/sec ±0.04% (98 runs sampled)
array of structure write x 722 ops/sec ±0.07% (96 runs sampled)
structure of array write x 802 ops/sec ±0.08% (97 runs sampled)
empty loop x 13,931 ops/sec ±0.08% (101 runs sampled)
empty loop + prng x 656 ops/sec ±0.24% (98 runs sampled)
Write fastest is empty loop
```

- Depending on what you want to optimize (calculation or storage), I think that more experiments unrolling the loops manually would be valuable, especially for non-SOA/AOS types like:
```
for (let i = 0; i < NUM_ELEMENTS / 5; i+=5) {
  arrayNumbers[i    ] = (Math.random() * Number.MAX_SAFE_INTEGER) | 0;
  arrayNumbers[i + 1] = (Math.random() * Number.MAX_SAFE_INTEGER) | 0;
  arrayNumbers[i + 2] = (Math.random() * Number.MAX_SAFE_INTEGER) | 0;
  arrayNumbers[i + 3] = (Math.random() * Number.MAX_SAFE_INTEGER) | 0;
  arrayNumbers[i + 4] = (Math.random() * Number.MAX_SAFE_INTEGER) | 0;
}
```
- For WebGL, I end up having to toss everything in a typed array prior to rendering anyway. Keep in mind the final output requirements.
- For Node.js in particular, typed arrays _seem_ like something that is lowish level and may have significant platform differences. If the actual app will run on Node.js, great. If not, try to test on the platform it will run on.

**Comment by joakin** [comment]
Thanks for looking into it, very useful!
